### ISSUE TITLE
Why should I use this one instead of the original one?

### ISSUE THREAD

**Issue by kumaranvpl** [Elcomerz/angular5-data-table-custom#1]
What is so special about this package comparing to the original one?
Why should I use this one over the original one?

**Comment by Elcomerz** [comment]
The original package doesn't have scrolling and table sizing options.
I have added these to this version so that we can customise it more.

**Comment by kumaranvpl** [comment]
OMG. This is a worse way to add a feature.
Imagine what would happen if everyone creates a fork whenever they develop a fix or a new feature.
You should create a pull request to the original code base with your modifications.
And this issue isn't resolved yet. So, reopen the issue.
